import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// PWA config, hardened in P8 (SPEC.md §11). The exit criterion is an install
// to the iQOO home screen followed by a correct verdict in airplane mode, so
// every choice below is made against that sentence.
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      devOptions: { enabled: false },
      manifest: {
        // `id` pins the app's identity across deploys. Without it the identity
        // is derived from start_url, so changing start_url later would strand
        // the copy already installed on the demo phone as a second app.
        id: '/',
        name: 'Kavach — scam message checker',
        short_name: 'Kavach',
        description:
          'Check whether a message is a scam. Runs on your phone, works offline.',
        // Matches --bg in tokens.css and the meta tag in index.html.
        theme_color: '#0B0B0C',
        background_color: '#0B0B0C',
        display: 'standalone',
        // A judge holding the phone should never be able to rotate the pitch
        // into a landscape layout nothing was checked at (§12 runs at 412×915).
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        lang: 'en-IN',
        categories: ['utilities', 'security'],
        // Generated by `npm run icons` from the same paths as ShieldLogo.
        //
        // Chrome on Android will not offer to install without a 192 and a 512,
        // and without a `maskable` entry it composites the `any` icon onto a
        // white circle — a dark square mark on a white disc, which is how a
        // careless PWA announces itself on a home screen. Both purposes ship.
        icons: [
          { src: '/icons/icon-96.png', sizes: '96x96', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/icons/icon-maskable-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icons/icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icons/icon-monochrome-96.png',
            sizes: '96x96',
            type: 'image/png',
            purpose: 'monochrome',
          },
          {
            src: '/icons/icon-monochrome-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'monochrome',
          },
        ],
        shortcuts: [
          {
            name: 'Check Message',
            short_name: 'Check',
            description: 'Scan and verify a suspicious message',
            url: '/',
            icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }],
          },
        ],
      },
      workbox: {
        // Model weights live in IndexedDB, not the SW cache. Never let Workbox
        // try to precache model shards (§8.1).
        //
        // `png` is here for the icon set only — roughly 40 KB, and it makes the
        // installed shell self-contained. `maximumFileSizeToCacheInBytes` below
        // is what stops a future large asset riding in on this pattern.
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],

        // `/api/analyze` is the cloud engine (§8.2). It is a fetch, not a
        // navigation, so the SPA fallback would not normally catch it — this is
        // belt and braces so a cloud call offline fails as a failed fetch that
        // the orchestrator can silently fall back from (D2), rather than
        // resolving to index.html and being parsed as a malformed engine reply.
        navigateFallbackDenylist: [/^\/api\//],

        // The inference runtimes are a ~6 MB chunk reached only from the
        // dev-only /dev/llm spike, so precaching them would add 6 MB to every
        // install for a route no user visits.
        //
        // P7 REVISITS THIS. Once LocalDetector is real, the runtime is on the
        // critical path for the offline demo (D6, P8) and must be cached — by
        // raising the size cap, or by runtime-caching it on first use so the
        // install stays small. Deleting these lines without making that
        // decision will silently break the airplane-mode beat.
        globIgnores: ['**/llm-runtime-*.js'],
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,

        // ...but the airplane-mode beat needs it offline. Caching it on first
        // use keeps the install small and still leaves the app fully offline
        // from the second run, which is exactly when the demo needs it. Model
        // weights are not here: WebLLM stores those itself (§8.1).
        runtimeCaching: [
          {
            urlPattern: /\/assets\/llm-runtime-.*\.js$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kavach-llm-runtime',
              expiration: { maxEntries: 2 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // Archivo carries the wordmark and the verdict headline (index.html).
          // It degrades to the platform face if it never loads, so this is not
          // a correctness fix — but on stage the offline run must look like the
          // online run, and an unstyled headline mid-demo reads as a fault.
          // Cached on first online paint; served from cache forever after.
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\//,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'kavach-font-css',
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\//,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kavach-font-files',
              expiration: { maxEntries: 8, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  build: {
    rollupOptions: {
      output: {
        // Named so the service worker can reason about them; see globIgnores.
        manualChunks(id) {
          if (id.includes('@mlc-ai/web-llm') || id.includes('@mediapipe/tasks-genai')) {
            return 'llm-runtime'
          }
          return undefined
        },
      },
    },
  },
  server: {
    // Needed to open the dev server from the phone on the same network.
    host: true,
    watch: {
      ignored: ['**/.chrome-cdp-profile/**', '**/screenshots/**'],
    },
  },
})
